server:
  port: 9002
  tomcat:
    threads:
      max: 10

management:
  health:
    elasticsearch:
        enabled: false
  endpoints:
    web.exposure:
      include: "*"

fhir:
  server:
    name: Health Administration Events and Documents
    baseUrl: http://localhost:9002
    version: 1.0.13

###Remote terminology validation:

##Example without auth:
#terminology:
#  url: https://r4.ontoserver.csiro.au/fhir

##Example with auth:
#terminology:
#  url: https://ontology.nhs.uk/authoring/fhir/
#  authorization:
#    tokenUrl: https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token
#    clientId: test
#    clientSecret: test
